### ISSUE TITLE
Performance is a tad slow

### ISSUE THREAD

**Issue by ghuntley** [justinwoo/format-nix#24] opened 2019-06-12 12:15 UTC
> $ time ./result/bin/format-nix ../nix/packages.nix 
> formatted ../nix/packages.nix.
> 
> real    0m6.232s
> user    0m6.458s
> sys     0m0.261s

Against https://github.com/digital-asset/daml/blob/master/nix/packages.nix

**Comment by justinwoo** [comment] 2019-06-12 12:36
Should be run with node profiling tools to find out what is actually the cause of problems, but the most likely problem spots:

* conversion of array to list when not very necessary https://github.com/justinwoo/format-nix/blob/master/src/FormatNix.purs#L148 (could use guards of Array.index)
* the naive implementation of pretty printer https://github.com/justinwoo/purescript-motsunabe/blob/master/src/Motsunabe.purs

**Comment by justinwoo** [comment] 2019-06-12 12:39
```
馬 ~/Code/format-nix master 異物 (1) $ time node --prof bin/index.js test/example-packages.nix
formatted test/example-packages.nix.

real    0m5.262s
user    0m5.735s
sys     0m0.214s
```

**Comment by justinwoo** [comment] 2019-06-12 12:53
good news, i just profiled it and it's really just that the pretty printer library is really slow. so ideally someone should either fix or replace https://github.com/justinwoo/purescript-motsunabe

**Comment by justinwoo** [comment] 2019-06-13 14:36
also good news: it seems i can just apply Data.Lazy to speed this up basically a thousand fold, thanks to no longer doing eager evaluation. I was doing some testing and found there were well over 14 million computations being done for no reason in a given alternatives problem space.

compare:

before:

![Screenshot from 2019-06-13 16-29-26](https://user-images.githubusercontent.com/2396926/59441656-38278d00-8df9-11e9-968e-f1bfac2024ce.png)
![Screenshot from 2019-06-13 16-30-00](https://user-images.githubusercontent.com/2396926/59441670-3cec4100-8df9-11e9-9bdf-7ee6aeba52dc.png)

after:

![Screenshot from 2019-06-13 16-29-50](https://user-images.githubusercontent.com/2396926/59441697-4aa1c680-8df9-11e9-9abb-bb1db70f9496.png)
![Screenshot from 2019-06-13 16-29-45](https://user-images.githubusercontent.com/2396926/59441699-4b3a5d00-8df9-11e9-9bf9-536973edb329.png)

i should be able to just patch my upstream library and get this working soon.

**Comment by justinwoo** [comment] 2019-06-13 15:48
here's my PR which updates the library https://github.com/justinwoo/format-nix/pull/25

changes upstream here https://github.com/justinwoo/purescript-motsunabe/commit/6b0d87bc1725f7f9ab53d1c71ed7e92bc287b22d

**Comment by justinwoo** [comment] 2019-06-14 08:53
@ghuntley this is in master now, so it should work fine:

```
馬 ~/Code/format-nix master $ wget https://raw.githubusercontent.com/digital-asset/daml/master/nix/packages.nix --quiet -O test-packages.nix
馬 ~/Code/format-nix master 異物 $ time node ./bin/output.js test-packages.nix
formatted test-packages.nix.

real    0m0.106s
user    0m0.094s
sys     0m0.018s
```

**Comment by justinwoo** [comment] 2019-06-24 21:49
@ghuntley I'll close this issue now since I believe it is solved. Let me know if you've tried this and found another issue.

**Closed as completed by justinwoo** 2019-06-24 21:49 UTC
Labels: bug, help wanted
